#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
convert.py — 将 articles/md 下的 Markdown 文章批量转换为赛博朋克风格的 HTML。

功能:
  1. 读取 articles/md/*.md,每篇生成一个 articles/htmls/<stem>.html
  2. 风格与 index.html / zh.html 一致(复用 css/style.css + css/article.css)
  3. 随机从 images/resource 选择一张图作为背景
  4. 支持 Markdown 图片、表格、代码块,公式通过 KaTeX 渲染($...$ / $$...$$ / \\(..\\) / \\[..\\])
  5. 每个页面带 "返回主页" 按钮(导航栏 + 悬浮按钮),指向 index.html

用法:
  python3 articles/tools/convert.py
"""

import argparse
import html
import json
import random
import re
import sys
from datetime import datetime
from pathlib import Path

try:
    import markdown
except ImportError:
    sys.exit("缺少依赖: 请先安装 markdown 库  ->  pip install markdown")

# ---------------------------------------------------------------------------
# 路径(基于脚本位置定位仓库根目录,保证在任意 cwd 下都能运行)
# ---------------------------------------------------------------------------
ROOT = Path(__file__).resolve().parents[2]          # articles/tools/ -> 仓库根
MD_DIR = ROOT / "articles" / "md"
OUT_DIR = ROOT / "articles" / "htmls"
RES_DIR = ROOT / "images" / "resource"
ARTICLE_CSS = ROOT / "css" / "article.css"
MANIFEST_JS = "articles.js"                        # 文章清单,供主页导航栏下拉列表加载

IMG_EXTS = {".jpg", ".jpeg", ".png", ".webp", ".gif", ".avif"}

# ---------------------------------------------------------------------------
# 数学公式保护:在 markdown 转换前把公式替换成占位符,转换后再还原,
# 避免 $x_i^2$ 中的下划线/星号等被 markdown 误解析。
# ---------------------------------------------------------------------------
FENCE_RE = re.compile(r"(```.*?```|~~~.*?~~~)", re.S)
INLINE_CODE_RE = re.compile(r"`[^`\n]+`")
DISPLAY_MATH_RE = re.compile(r"\$\$(.+?)\$\$", re.S)
INLINE_MATH_RE = re.compile(r"(?<![\\$\w])\$(?!\s)(.+?)(?<!\s)\$(?!\w)")
PAREN_MATH_RE = re.compile(r"\\\((.+?)\\\)", re.S)
BRACKET_MATH_RE = re.compile(r"\\\[(.+?)\\\]", re.S)


def extract_math(text: str):
    """把代码块/行内代码/公式全部替换为占位符,返回 (处理后文本, 占位符表)。"""
    store: dict[str, str] = {}

    def stash(raw: str) -> str:
        key = f"ZQXMATH{len(store)}XZ"
        store[key] = raw
        return key

    parts = FENCE_RE.split(text)
    processed = []
    for part in parts:
        if not part:
            continue
        # 代码块原样保护
        if part.startswith("```") or part.startswith("~~~"):
            processed.append(part)
            continue
        # 行内代码保护
        part = INLINE_CODE_RE.sub(lambda m: stash(m.group(0)), part)
        # 公式保护(display 优先,避免 $$ 被当成两个 $)
        part = DISPLAY_MATH_RE.sub(lambda m: stash(m.group(0)), part)
        part = PAREN_MATH_RE.sub(lambda m: stash(m.group(0)), part)
        part = BRACKET_MATH_RE.sub(lambda m: stash(m.group(0)), part)
        part = INLINE_MATH_RE.sub(lambda m: stash(m.group(0)), part)
        processed.append(part)

    return "".join(processed), store


def restore_math(html_text: str, store: dict[str, str]) -> str:
    """把占位符还原为 HTML 转义后的公式原文,交给前端 KaTeX 渲染。"""
    for key, raw in store.items():
        html_text = html_text.replace(key, html.escape(raw))
    return html_text


# ---------------------------------------------------------------------------
# 文章元信息
# ---------------------------------------------------------------------------
H1_RE = re.compile(r"^#\s+(.+?)\s*#*\s*$", re.M)


def article_meta(md_text: str, md_path: Path):
    """提取标题(首个 H1,否则用文件名)与摘要(首个非标题段落)。"""
    m = H1_RE.search(md_text)
    title = m.group(1).strip() if m else md_path.stem
    # 标题已用于 section-title,正文里去掉首个 H1 避免重复
    if m:
        md_text = md_text[: m.start()] + md_text[m.end():]

    desc = ""
    for block in re.split(r"\n\s*\n", md_text):
        block = block.strip()
        if block and not block.startswith(("#", "```", "~~~", "!", "|", ">")):
            desc = re.sub(r"[*_`$\[\]]", "", block)[:120]
            break
    if not desc:
        desc = f"lordrebel 的文章 — {title}"

    date_str = datetime.fromtimestamp(md_path.stat().st_mtime).strftime("%Y.%m.%d")
    return title, desc, date_str, md_text


# ---------------------------------------------------------------------------
# 配套样式(仅首次生成,之后可手动修改 css/article.css)
# ---------------------------------------------------------------------------
ARTICLE_CSS_TEXT = """\
/* ===== Article Page Styles (generated by articles/tools/convert.py) ===== */

.article-content {
  position: relative;
  z-index: 1;
  font-size: 1.08rem;
  line-height: 1.9;
  color: var(--text-main);
}

.article-content p { margin: 1.1rem 0; }

.article-content h1, .article-content h2, .article-content h3,
.article-content h4, .article-content h5, .article-content h6 {
  font-family: 'Orbitron', 'Noto Sans SC', monospace;
  color: var(--neon-cyan);
  text-shadow: 0 0 10px rgba(0, 240, 255, 0.35);
  letter-spacing: 1px;
  margin: 2.2rem 0 1rem;
}

.article-content h2 {
  border-bottom: 1px solid var(--border-glow);
  padding-bottom: 0.5rem;
}

.article-content h3 { color: var(--neon-magenta); text-shadow: 0 0 10px rgba(255, 0, 229, 0.35); }

.article-content a {
  color: var(--neon-cyan);
  text-decoration: none;
  border-bottom: 1px dashed var(--border-glow);
  transition: all 0.3s;
}
.article-content a:hover {
  color: var(--neon-magenta);
  text-shadow: 0 0 8px var(--neon-magenta);
  border-bottom-color: var(--neon-magenta);
}

/* 图片 */
.article-content img {
  display: block;
  max-width: 100%;
  height: auto;
  margin: 1.5rem auto;
  border: 1px solid var(--border-glow);
  border-radius: 6px;
  box-shadow: 0 0 18px rgba(0, 240, 255, 0.2);
}

/* 表格 */
.article-content table {
  width: 100%;
  border-collapse: collapse;
  margin: 1.5rem 0;
  background: var(--bg-panel);
  border: 1px solid var(--border-glow);
  box-shadow: 0 0 15px rgba(0, 240, 255, 0.12);
}
.article-content th {
  font-family: 'Orbitron', 'Noto Sans SC', monospace;
  color: var(--neon-cyan);
  letter-spacing: 1px;
  text-transform: uppercase;
  border-bottom: 2px solid var(--neon-cyan);
  padding: 0.7rem 1rem;
  text-align: left;
}
.article-content td {
  padding: 0.6rem 1rem;
  border-bottom: 1px solid rgba(0, 240, 255, 0.15);
}
.article-content tr:hover td { background: rgba(0, 240, 255, 0.05); }

/* 代码 */
.article-content code {
  font-family: 'Fira Code', 'Consolas', monospace;
  font-size: 0.92em;
  color: var(--neon-green);
  background: rgba(0, 240, 255, 0.08);
  border: 1px solid rgba(0, 240, 255, 0.2);
  border-radius: 4px;
  padding: 0.1rem 0.4rem;
}
.article-content pre {
  background: rgba(5, 5, 15, 0.92);
  border: 1px solid var(--border-glow);
  border-left: 3px solid var(--neon-magenta);
  border-radius: 6px;
  padding: 1rem 1.2rem;
  margin: 1.5rem 0;
  overflow-x: auto;
  box-shadow: 0 0 15px rgba(0, 240, 255, 0.1);
}
.article-content pre code {
  background: transparent;
  border: none;
  padding: 0;
}
/* highlight.js 主题适配:沿用 pre 自身的赛博朋克背景 */
.article-content pre code.hljs {
  background: transparent;
  padding: 0;
}

/* 引用 / 列表 / 分割线 */
.article-content blockquote {
  border-left: 3px solid var(--neon-purple);
  background: rgba(176, 38, 255, 0.08);
  padding: 0.8rem 1.2rem;
  margin: 1.5rem 0;
  color: var(--text-dim);
}
.article-content ul, .article-content ol { margin: 1rem 0 1rem 1.5rem; }
.article-content li { margin: 0.4rem 0; }
.article-content hr {
  border: none;
  height: 1px;
  margin: 2.5rem 0;
  background: linear-gradient(90deg, transparent, var(--neon-cyan), var(--neon-magenta), transparent);
}

/* 悬浮返回按钮 */
.back-home-float {
  position: fixed;
  right: 1.4rem;
  bottom: 1.4rem;
  z-index: 1200;
  font-family: 'Orbitron', 'Noto Sans SC', monospace;
  font-size: 0.85rem;
  font-weight: 700;
  letter-spacing: 1px;
  color: var(--neon-cyan);
  background: rgba(10, 10, 18, 0.9);
  border: 1px solid var(--neon-cyan);
  border-radius: 6px;
  padding: 0.55rem 1rem;
  text-decoration: none;
  box-shadow: 0 0 15px rgba(0, 240, 255, 0.3);
  transition: all 0.3s;
}
.back-home-float:hover {
  background: var(--neon-cyan);
  color: var(--bg-dark);
  box-shadow: 0 0 20px var(--neon-cyan);
}

/* 简洁模式 */
body.minimal .article-content img { box-shadow: none; }
body.minimal .article-content table { box-shadow: none; background: transparent; }
body.minimal .back-home-float { box-shadow: none; }

/* ===== 文章页布局:短文时页脚贴底 + 限制阅读宽度 ===== */
body {
  display: flex;
  flex-direction: column;
  min-height: 100vh;
}
.article-section { max-width: 900px; }
.footer { margin-top: auto; }

/* ===== 字号缩放控制 ===== */
.font-zoom {
  display: flex;
  gap: 0.4rem;
  align-items: center;
}
.zoom-btn {
  font-family: 'Orbitron', monospace;
  padding: 0.3rem 0.7rem;
  border: 1px solid var(--neon-yellow);
  border-radius: 4px;
  background: transparent;
  color: var(--neon-yellow);
  font-size: 0.8rem;
  font-weight: 700;
  cursor: pointer;
  letter-spacing: 1px;
  transition: all 0.3s;
}
.zoom-btn:hover,
.zoom-btn.active {
  background: var(--neon-yellow);
  color: var(--bg-dark);
  box-shadow: 0 0 12px var(--neon-yellow);
}
"""

# ---------------------------------------------------------------------------
# HTML 模板(占位符用 {{XXX}},避免与 CSS/JS 花括号冲突)
# ---------------------------------------------------------------------------
TEMPLATE = """<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="{{DESC}}">
  <title>{{TITLE}} // lordrebel</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Orbitron:wght@400;700;900&family=Rajdhani:wght@400;600;700&family=Noto+Sans+SC:wght@400;600;700&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="../../css/style.css">
  <link rel="stylesheet" href="../../css/article.css">
  <link rel="icon" type="image/png" href="../../images/avatar/avatar1.png">
  <!-- KaTeX 公式渲染 -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/katex.min.css">
  <script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/katex.min.js"></script>
  <script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/contrib/auto-render.min.js"></script>
  <!-- highlight.js 代码语法高亮 -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@11.9.0/build/styles/atom-one-dark.min.css">
  <script defer src="https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@11.9.0/build/highlight.min.js"></script>
</head>
<body>

  <!-- Background -->
  <div class="bg-slideshow">
    <div class="bg-slide active" style="background-image: url('{{BG_IMG}}')"></div>
  </div>
  <div class="bg-overlay"></div>

  <!-- Navigation -->
  <nav class="nav-bar">
    <div class="nav-inner">
      <a href="../../index.html" class="nav-logo">lordrebel</a>
      <input type="checkbox" id="nav-check" class="nav-check">
      <label for="nav-check" class="nav-hamburger">☰</label>
      <ul class="nav-links">
        <li><a href="../../index.html" class="lang-toggle">⌂ 返回主页</a></li>
        <li class="font-zoom">
          <button class="zoom-btn" type="button" data-zoom="out" title="缩小字号">A−</button>
          <button class="zoom-btn" type="button" data-zoom="reset" title="默认字号">A</button>
          <button class="zoom-btn" type="button" data-zoom="in" title="放大字号">A+</button>
        </li>
        <li><button class="style-toggle" onclick="document.body.classList.toggle('minimal');this.textContent=document.body.classList.contains('minimal')?'炫酷':'简洁'">简洁</button></li>
      </ul>
    </div>
  </nav>

  <!-- Decorative side bars -->
  <div class="deco-bar-left"></div>
  <div class="deco-bar-right"></div>

  <!-- Article -->
  <section class="section has-bg article-section" id="article">
    <h2 class="section-title"><span class="num">{{DATE}}</span>{{TITLE}}</h2>
    <div class="article-content">
{{CONTENT}}
    </div>
  </section>

  <!-- Footer -->
  <footer class="footer">
    <p>© 2026 <span class="neon">lordrebel</span> // 由 <span class="neon">GitHub Pages</span> 驱动 // Built with ❤ & neon</p>
  </footer>

  <!-- 悬浮返回主页按钮 -->
  <a href="../../index.html" class="back-home-float">← 返回主页</a>

  <!-- 字号缩放(5 档,localStorage 记忆) -->
  <script>
    (function() {
      var steps = [0.85, 1, 1.15, 1.3, 1.5];
      var idx = 1;
      try {
        idx = parseInt(localStorage.getItem('articleZoom') || '1', 10) || 1;
        idx = Math.max(0, Math.min(steps.length - 1, idx));
      } catch (e) { idx = 1; }
      var content = document.querySelector('.article-content');
      var btns = document.querySelectorAll('.zoom-btn');

      function apply() {
        if (content) content.style.fontSize = (1.08 * steps[idx]).toFixed(2) + 'rem';
        try { localStorage.setItem('articleZoom', String(idx)); } catch (e) {}
        btns.forEach(function(b) {
          b.classList.toggle('active', b.dataset.zoom === 'reset' && idx === 1);
        });
      }

      btns.forEach(function(b) {
        b.addEventListener('click', function() {
          var z = b.dataset.zoom;
          if (z === 'in') idx = Math.min(steps.length - 1, idx + 1);
          else if (z === 'out') idx = Math.max(0, idx - 1);
          else idx = 1;
          apply();
        });
      });
      apply();
    })();
  </script>

  <!-- 代码语法高亮(带 language-xxx 类则按指定语言,否则自动检测) -->
  <script>
    document.addEventListener("DOMContentLoaded", function() {
      if (typeof hljs !== "undefined") {
        document.querySelectorAll(".article-content pre code").forEach(function(b) {
          hljs.highlightElement(b);
        });
      }
    });
  </script>

  <!-- KaTeX 自动渲染 -->
  <script>
    document.addEventListener("DOMContentLoaded", function() {
      if (typeof renderMathInElement === "function") {
        renderMathInElement(document.body, {
          delimiters: [
            { left: "$$", right: "$$", display: true },
            { left: "\\\\[", right: "\\\\]", display: true },
            { left: "\\\\(", right: "\\\\)", display: false },
            { left: "$", right: "$", display: false }
          ],
          throwOnError: false
        });
      }
    });
  </script>

</body>
</html>
"""


def ensure_article_css() -> None:
    """首次运行时生成 css/article.css(已存在则不覆盖,便于手动定制)。"""
    if not ARTICLE_CSS.exists():
        ARTICLE_CSS.parent.mkdir(parents=True, exist_ok=True)
        ARTICLE_CSS.write_text(ARTICLE_CSS_TEXT, encoding="utf-8")
        print(f"[css] 生成样式文件: {ARTICLE_CSS.relative_to(ROOT)}")


def pick_random_bg() -> str:
    """从 images/resource 随机挑一张背景图,返回相对 articles/htmls 的路径。"""
    images = [p for p in RES_DIR.iterdir() if p.suffix.lower() in IMG_EXTS] if RES_DIR.is_dir() else []
    if not images:
        return ""
    chosen = random.choice(images)
    rel = chosen.relative_to(ROOT).as_posix()
    print(f"[bg]  随机背景: {rel}")
    return f"../../{rel}"


def convert_file(md_path: Path, out_path: Path) -> None:
    md_text = md_path.read_text(encoding="utf-8")
    title, desc, date_str, body = article_meta(md_text, md_path)

    protected, store = extract_math(body)
    content_html = markdown.markdown(
        protected,
        extensions=["extra", "toc", "sane_lists"],  # extra 含 tables / fenced_code
        output_format="html5",
    )
    content_html = restore_math(content_html, store)

    # 缩进正文,保持生成文件排版整洁
    content_html = "\n".join("      " + line if line.strip() else "" for line in content_html.splitlines())

    page = (
        TEMPLATE.replace("{{DESC}}", html.escape(desc))
        .replace("{{TITLE}}", html.escape(title))
        .replace("{{DATE}}", date_str)
        .replace("{{BG_IMG}}", pick_random_bg())
        .replace("{{CONTENT}}", content_html)
    )

    out_path.write_text(page, encoding="utf-8")
    print(f"[ok]  {md_path.relative_to(ROOT)}  ->  {out_path.relative_to(ROOT)}")
    return {"title": title, "file": out_path.name, "date": date_str}


def write_articles_js(metas: list[dict], out_dir: Path) -> None:
    """生成文章清单 articles/htmls/articles.js,供主页导航栏「文章」下拉列表加载。

    GitHub Pages 是纯静态站点,无法列目录,因此用 JS 变量清单代替:
    主页通过 <script src="articles/htmls/articles.js"> 加载全局变量 ARTICLES。
    """
    items = ",\n".join(
        "  {{ \"title\": {title}, \"file\": {file}, \"date\": {date} }}".format(
            title=json.dumps(m["title"], ensure_ascii=False),
            file=json.dumps(m["file"], ensure_ascii=False),
            date=json.dumps(m["date"], ensure_ascii=False),
        )
        for m in metas
    )
    js = (
        "/* 文章清单 — 由 articles/tools/convert.py 自动生成,勿手动修改 */\n"
        "var ARTICLES = [\n" + items + "\n];\n"
    )
    manifest = out_dir / MANIFEST_JS
    manifest.write_text(js, encoding="utf-8")
    print(f"[js]  生成文章清单: {manifest.relative_to(ROOT)} ({len(metas)} 篇)")


def main() -> None:
    parser = argparse.ArgumentParser(description="Markdown 文章 -> 赛博朋克风格 HTML")
    parser.add_argument("--md-dir", type=Path, default=MD_DIR, help="Markdown 源目录")
    parser.add_argument("--out-dir", type=Path, default=OUT_DIR, help="HTML 输出目录")
    parser.add_argument("--seed", type=int, default=None, help="随机背景的随机种子(便于复现)")
    args = parser.parse_args()

    if args.seed is not None:
        random.seed(args.seed)

    md_dir: Path = args.md_dir
    out_dir: Path = args.out_dir
    if not md_dir.is_dir():
        sys.exit(f"源目录不存在: {md_dir}")

    md_files = sorted(md_dir.glob("*.md"))
    if not md_files:
        sys.exit(f"{md_dir} 下没有找到 .md 文件")

    out_dir.mkdir(parents=True, exist_ok=True)
    ensure_article_css()

    metas = []
    for md_path in md_files:
        metas.append(convert_file(md_path, out_dir / (md_path.stem + ".html")))

    # 按日期倒序排列,最新文章在前
    metas.sort(key=lambda m: m["date"], reverse=True)
    write_articles_js(metas, out_dir)

    print(f"\n完成: 共转换 {len(md_files)} 篇文章 -> {out_dir}")


if __name__ == "__main__":
    main()
